name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy
        run: mkdocs gh-deploy --force

      - name: Debug Commit Message
        env:
          MSG: ${{ github.event.head_commit.message }}
        run: echo "The message is... $MSG"

      - name: Notify Discord
        if: github.actor != 'github-actions[bot]' && success()
        env:
          MSG: ${{ github.event.head_commit.message }}
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if echo "$MSG" | grep -qi "\[notify\]"; then
            CLEAN_MSG=$(echo "$MSG" | sed 's/\[notify\]//gI' | sed '/^[[:space:]]*$/d' | sed 's/"/\\"/g')

            curl -X POST -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "Site Updated!",
                "description": "New changes were just pushed to the documentation by **'${{ github.actor }}'**.\n\n**Commit Message:**\n> '"$CLEAN_MSG"'\n\n **Links:**\n[View Changes]('${{ github.event.compare }}') | [View Live Site](https://botan14xd.github.io/BD2-Overview/)",
                "color": 3066993
              }]
            }' $WEBHOOK
          else
            echo "No [notify] tag found. Skipping Discord."
          fi