name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy
        run: mkdocs gh-deploy --force

      - name: Debug Commit Message
        env:
          MSG: ${{ github.event.head_commit.message }}
        run: echo "The message is... $MSG"

      - name: Notify Discord on Major Features
        if: |
          github.actor != 'github-actions[bot]' && 
          contains(github.event.head_commit.message, '[notify]') && 
          success() 
        uses: rjstone/discord-webhook-notify@v2
        with:
          severity: info
          text: "**Site Updated!**"
          details: |
            New changes were just pushed to the documentation by **${{ github.actor }}**.
            
            **Commit Message:**
            > ${{ github.event.head_commit.message }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}